### ISSUE TITLE
SINTESIS_GENARO SANTIAGO VALENTÍN

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Valentiin01#1]
[SINSTESIS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Valentiin01/files/12771063/SINSTESIS.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hehco y revisado...
